# Generated by Django 4.0.4 on 2022-05-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='rank',
            field=models.IntegerField(default=1),
        ),
    ]
