# Generated by Django 4.0.4 on 2022-05-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_userdetails_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewUserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('score', models.IntegerField()),
            ],
        ),
    ]
